---
- name: Install Vim
  package:
    name: vim
    state: present
- name: Install tmux
  package:
    name: tmux
    state: present
- name: Install htop
  package:
    name: htop
    state: present
- name: Install ZSH
  package:
    name: zsh
    state: present
- name: Fetch zsh dotfile
  get_url:
    url: 'https://raw.githubusercontent.com/torbsch/setup/master/roles/common/files/.zshrc'
    dest: ~/.zshrc
    # Missing:
    # - Owner/chmod
    # - Install oh-my-zsh
    # - zsh theme
    # - ZSH as default
