---
- name: Install Vim
  package:
    name: vim
    state: present
- name: Install tmux
  package:
    name: tmux
    state: present
- name: Install htop
  package:
    name: htop
    state: present
- name: Install ZSH
  package:
    name: zsh
    state: present
- name: Fetch zsh dotfile
  get_url:
    url: 'https://raw.githubusercontent.com/torbsch/setup/master/roles/common/files/.zshrc'
    dest: ~/.zshrc
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644
- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
  become_user: "{{ ansible_env.SUDO_USER }}"
    # Missing:
    # - zsh theme
    # - ZSH as default
