---
- name: Ensure Git is installed
  apt:
    name: git
    state: present
  become: yes

- name: Ensure tig is installed
  apt:
    name: tig
    state: present
  become: yes

- name: Ensure Vim is installed
  apt:
    name: vim
    state: present
  become: yes

- name: Ensure tmux is installed
  apt:
    name: tmux
    state: present
  become: yes

- name: Ensure htop is installed
  apt:
    name: htop
    state: present
  become: yes

- name: Ensure pip3 is installed
  apt:
    name: python3-pip
    state: present
  become: yes

- name: Ensure Ranger is installed
  apt:
    name: ranger
    state: present
  become: yes

- name: Ensure lynx is installed
  apt:
    name: lynx
    state: present
  become: yes
