---
- name: Install Git
  package:
    name: git
    state: present

- name: Install Vim
  package:
    name: vim
    state: present

- name: Install tmux
  package:
    name: tmux
    state: present

- name: Install htop
  package:
    name: htop
    state: present
