---
- name: Install Git
  apt:
    name: git
    state: present

- name: Install Vim
  apt:
    name: vim
    state: present

- name: Install tmux
  apt:
    name: tmux
    state: present

- name: Install htop
  apt:
    name: htop
    state: present
