---
- name: Install ZSH
  package:
    name: zsh
    state: present

- name: Copy zsh configuration file
  copy:
    src: .zshrc
    dest: /home/{{ sudo_user }}/.zshrc
    owner: "{{ sudo_user }}"
    group: "{{ sudo_user }}"
    mode: 0775

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "/home/{{ sudo_user }}/.oh-my-zsh"
    force: yes

- name: Sets attributes of zsh
  file:
    path: /home/{{ sudo_user }}/.oh-my-zsh
    owner: "{{ sudo_user }}"
    group: "{{ sudo_user }}"
    mode: 0755
    recurse: yes

- name: Install powerline-status
  pip:
    name: powerline-status
    state: present

- name: Install powerline fonts
  package:
    name: fonts-powerline
    state: present

- name: Download bullet-train zsh theme
  get_url:
    url: https://raw.githubusercontent.com/caiogondim/bullet-train.zsh/master/bullet-train.zsh-theme
    dest: /home/{{ sudo_user }}/.oh-my-zsh/themes/bullet-train.zsh-theme

- name: Sets attributes of bullet-train zsh theme
  file:
    path: /home/{{ sudo_user }}/.oh-my-zsh/themes/bullet-train.zsh-theme
    owner: "{{ sudo_user }}"
    group: "{{ sudo_user }}"
    mode: 0644

- name: Set zsh as default shell for user
  user:
    name: "{{ sudo_user }}"
    shell: /bin/zsh